window.sampledata = [ { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Greek Salad - Small',
    description: 'Lettuce, tomatoes, cucumbers, onions, house greek dressing, topped with feta cheese, greek olives, pepperoncini. Choice of small, large, small (served 5 people), or large (served 10 people).',
    price: 4.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Greek Salad - Large',
    description: 'Lettuce, tomatoes, cucumbers, onions, house greek dressing, topped with feta cheese, greek olives, pepperoncini. Choice of small, large, small (served 5 people), or large (served 10 people).',
    price: 7.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Gyro Salad',
    description: 'Sliced gyro meat (mixture of lamb and beef) served on Greek salad and side of house tzatziki sauce.',
    price: 8.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Grilled Chicken Salad',
    description: 'Grilled chicken breast served with Greek salad and side of house tzatziki sauce.',
    price: 8.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Grilled Lamb Salad',
    description: 'Grilled lamb tenderloin served with Greek salad and side of house tzatziki sauce.',
    price: 9.5 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Falafel Salad',
    description: 'Freshly fried 4 falafel patties served with Greek salad and side of house tzatziki sauce.',
    price: 7.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Prawn Salad',
    description: 'Grilled prawns served with Greek salad and side of house tzatziki sauce.',
    price: 9.5 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Lentil Soup - Cup',
    description: 'Choice of cup or bowl.',
    price: 2.5 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Lentil Soup - Bowl',
    description: 'Choice of cup or bowl.',
    price: 2.99 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Avgalemono - Cup',
    description: '(Chicken, Egg, Rice) Choice of cup or bowl.',
    price: 2.5 },
  { restaurant: 'Greek Express - Main St',
    location: 'Bellevue',
    item: 'Avgalemono - Bowl',
    description: '(Chicken, Egg, Rice) Choice of cup or bowl.',
    price: 2.99 }
];
